name: build-master

on:
  push:
    branches: 
      - master

concurrency:
  group: main
  cancel-in-progress: true
  
jobs:
  build:
    name: "Build & Release container"
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: [1.22.1, 1.24.0, 1.26.3, 1.27.5, 1.28.0]
    steps:
    - uses: actions/checkout@v4

    - name: Build container & Deploy
      run: |
        repo_owner=${{ github.repository }}
        repo_owner=${repo_owner,,}

        BUILDSTRING=static-nginx-${{matrix.version}}:master

        docker build . -t ghcr.io/$repo_owner/$BUILDSTRING --build-arg version=${{matrix.version}}
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        docker push ghcr.io/$repo_owner/$BUILDSTRING
        

