name: Build Tests

on:
  pull_request:

jobs:
  test_build_job:
    name: Test Build Versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [1.20.2, 1.22.1, 1.24.0, 1.25.1]      
    steps:
    - uses: actions/checkout@v3

    - name: Build container
      run: |
        repo_owner=${{ github.repository }}
        repo_owner=${repo_owner,,}

        docker build --build-arg version=${{matrix.version}} . -t ghcr.io/$repo_owner/static-nginx-${{matrix.version}}:${GITHUB_SHA::8}

          
