name: build-master

on:
  push:
    branches: 
      - master
jobs:
  build:
    name: "Build & Release container"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build container & Deploy
      run: |
        repo_owner=${{ github.repository }}
        repo_owner=${repo_owner,,}

        docker build . -t ghcr.io/$repo_owner/static-nginx:master
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        docker push ghcr.io/$repo_owner/static-nginx:master
        

