name: build-master

on:
  push:
    branches: 
      - master
jobs:
  build:
    name: "Build & Release container"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build container & Deploy
      run: |
        repo=${{ github.repository }}
        repo=${repo,,}

        docker build . -t ghcr.io/teddio/static-nginx:master
        echo ${{ secrets.PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker push ghcr.io/teddio/static-nginx:master
        

