name: Build Tests

on:
  pull_request:

jobs:
  test_build_job:
    name: Test Build Versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [1.27.3]
    steps:
    - uses: actions/checkout@v4

    - name: Build container
      run: |
        repo_owner=${{ github.repository }}
        repo_owner=${repo_owner,,}

        docker build --build-arg version=${{matrix.version}} . -t ghcr.io/$repo_owner/static-nginx-${{matrix.version}}:${GITHUB_SHA::8}
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        docker push ghcr.io/$repo_owner/${GITHUB_SHA::8}
          
