name: build-merge

on:
  pull_request:

jobs:
  test_build_job:
  name: "Test Builds"
  runs-on: ubuntu-latest

  strategy:
  matrix:
    version: [1.16.1, 1.18.0, 1.19.10, 1.20.0]      
  steps:
  - uses: actions/checkout@v2

  - name: Build container
    run: |
      repo_owner=${{ github.repository }}
      repo_owner=${repo_owner,,}

      docker build . -e version=${{matrix.version}} -t ghcr.io/$repo_owner/static-nginx:${GITHUB_SHA::8}

        
